### PR TITLE
add automake to generate Makefile.in from Makefile.am

### PR DESCRIPTION
**Pull request by tjyang**
Hi There

I am new comer to nagios-plugins git repo, please review this pull request so that following expected commands works.

./autogen.sh
make

currently, I need to run following 3 commands
automake
./autogent.sh
make

### CODE REVIEW

**Comment by sreinhardt** [comment]
Hello, sorry for the delay, working on several other projects at the moment hopefully soon to return. Anyway, on a fresh git pull or clone and while in the plugins root directory, the proper build commands are:
``` sh
./tools/setup
./configure --prefix=BASEDIRECTORY --with-cgiurl=SOMEURL
make
make install
make install-root
```
This should be covered here https://github.com/nagios-plugins/nagios-plugins#installation-instructions. Let me know if you have further issues, otherwise I'll close this in a week or so.

**Comment by tjyang** [comment]
Thanks for the pointer to installation URL.
I was hoping running autogen.sh will include all the needed works before "./configure && make && make install && make root".  
Can tools/setup be included into autogen.sh ?

**Comment by sreinhardt** [comment]
I can certainly take a look and see if this makes sense to do, but no promises until I do that. :)

**Comment by abrist** [comment]
tools/setup is already included in autogen.sh and has been for years:

$ grep tools autogen.sh
./tools/setup

**Pull request closed without merging**
