### PR TITLE
Fix for check_mysql not looking in correct path for my.cnf

### PR DESCRIPTION
**Pull request by scottwilkerson**
https://bugzilla.redhat.com/show_bug.cgi?id=1256731
https://bugs.centos.org/view.php?id=9333

### CODE REVIEW

**Comment by waja** [comment]
This was introduced by 5ed7194c7e1f6c46c9b40dccbe760dfef853bae1

**Comment by waja** [comment]
@jfrickson even this ... why is this PR closed?

**Comment by jfrickson** [comment]
Thought it was fixed by another commit. I will update the source manually. Sorry.

**Comment by waja** [comment]
@jfrickson you definitely should improve your workflow!

**Comment by jfrickson** [comment]
@waja well, I figured someone with as much experience as you wouldn't assume I applied it to master, so I figured I messed up. But I'm fairly new at git, so what do I know? Is it wrong to apply a pull request against master to a maintenance branch?

**Comment by waja** [comment]
@jfrickson at least, it would a good behavior to document in the issue, why you closed it. Cool would be, to point to what you've done to close it. Nothing related to git itself. This might also help YOU to know, why you have closed a ticket and what was your action.

Sorry when you feel offended, I thought I can help you and your project. But the more I'm trying to, I've the feeling that nobody at your project is interested into this.

**Comment by jfrickson** [comment]
@waja no, I wasn't offended. Sorry if it came off that way. Good suggestion to document it in the close. I'll do that from now on. Thanks.

**Comment by waja** [comment]
@jfrickson you can point to a commit by just putting the SHA into the ticket like this: d0ed22a2ddf6b8d3aa63ce58a7898d5953a94cc0

Even you can close a ticket by a commit message: https://help.github.com/articles/closing-issues-via-commit-messages/
As written there, the ticket will stay open until the commit hits the branch configured at github as 'default branch'. Actual your default branch is master, so closing via a commit message in maint doesn't close the ticket (until it's cherry-picket into master or maint merged back into master [which is indeed a good idea])

**Pull request closed without merging**
