### PR TITLE
If retries is 0, wait for timeout to elapse at least once.

### PR DESCRIPTION
**Pull request by j41785**

### CODE REVIEW

**Comment by sreinhardt** [comment]
Just wanted to make an update. The timeout state branch has been merged into the 2.1 beta branch and we would appreciate a test to see if your case has been resolve. I will do the same, but wanted to be sure you got a notification.

**Comment by j41785** [comment]
Thanks for following up. I'll take a look today.

Justin

Just wanted to make an update. The timeout state branch has been merged
into the 2.1 beta branch and we would appreciate a test to see if your case
has been resolve. I will do the same, but wanted to be sure you got a
notification.

—
Reply to this email directly or view it on GitHub
<https://github.com/nagios-plugins/nagios-plugins/pull/51#issuecomment-72654596>
.

**Comment by j41785** [comment]
It still has the same off by 1 error.  snmpget accepts a retry count of 0 and so too should the check code.  See line 244:
https://github.com/nagios-plugins/nagios-plugins/blob/2.1.0-beta-RC1/plugins/check_snmp.c#L244

Changing it to this will include the time for the first try as well:
command_interval = timeout_interval / (retries + 1);

**Comment by abrist** [comment]
Fixed in https://github.com/nagios-plugins/nagios-plugins/commit/cf98f99d76bf5fd1e9344d60bb88e4e07d1eeb81

Thanks!

**Pull request closed without merging**
