### PR TITLE
fix some gcc-7.3 warnings

### PR DESCRIPTION
**Pull request by mjtrangoni**
I fixed some trivial `gcc` warnings. Please feel free to merge or cherry-pick some.

Thanks!

### CODE REVIEW

**Comment by hedenface** [comment]
Thanks! Can you resolve the conflicts for `maint` so that I can review and merge?

**Comment by mjtrangoni** [comment]
@hedenface thanks! It should be working now. I forgot you work with the `maint` branch.

**Comment by mjtrangoni** [comment]
@hedenface this is a little chaos here, I will be fixing and rebasing this soon.
What's about setting up TravisCI here too?

**Comment by hedenface** [comment]
I had asked @box293 to look into creating one for plugins. If you'd like to work on that, feel free!

All of the OSS projects will have some form of testing in the next few months - along with a more consistent layout and the beginnings of consistency throughout the codebase(s). I'm actually working on the style guide for Core as we speak and that should be available soon.

**Comment by chicks-net** [comment]
Where will the style guide be once it is available?  Or where should we keep an eye out for the style guide announcement?

**Comment by hedenface** [comment]
It will be available in each of the repos as `CODING_STYLE.md` once complete.

**Pull request merged**
