### PR TITLE
[RFC] check_disk_smb.pl: fallback to non-utf8 when utf8::all is missing

### PR DESCRIPTION
**Pull request by tmzullinger**
Support for utf8 host, share, and user names was added in c8714d72
("check_disk_smb.pl: added utf support & blacklisting characters instead
of expanding the whitelist", 2019-08-02).  This adds a new dependency on
the utf8::all perl module.

Make this requirement optional and fall back gracefully to the previous
non-utf8 matching for host, share, and user names.

### CODE REVIEW

**Comment by tmzullinger** [comment]
I ran into this new dependency while updating nagios-plugins from the EPEL repository on CentOS 6, where the perl `utf8::all` module is not currently available.

I'm not a regular user of `check_disk_smb` nor a regular perl coder anymore, so this change might not be the best way to achieve the goal.  It may also not be desirable to make this optional (though IMO it is; I think adding a new hard dependency to a plugin on the maint branch doesn't seem ideal).

Any thoughts on the goal or the implementation @sawolf or @k0ste?

**Comment by sawolf** [comment]
Thanks for reporting this. I'll figure something out

**Comment by tmzullinger** [comment]
Ahhh, so the two changes in c8714d72 ("check_disk_smb.pl: added utf support & blacklisting characters instead of expanding the whitelist", 2019-08-02) are a bit orthogonal.  I made things _way_ more complicated in my patch because I thought the script needed to use different regexp patterns depending on the availability of the `utf8::all` module.  D'oh!

I'll give this a test shortly and see if it helps rpm avoid the `utf8::all` dependency.  Thanks!

**Comment by tmzullinger** [comment]
The code on the current maint branch doesn't solve the problem.  It still tries and fails to import `utf8::all` when it is not available.  This change should solve the issue with and without the module available:

```diff
diff --git i/plugins-scripts/check_disk_smb.pl w/plugins-scripts/check_disk_smb.pl
index fa99a361..63617156 100755
--- i/plugins-scripts/check_disk_smb.pl
+++ w/plugins-scripts/check_disk_smb.pl
@@ -19,10 +19,7 @@
 #
 
 require 5.004;
-eval "use utf8::all";
-if ( $@ ) {
-    use utf8::all;
-}
+eval { require utf8::all; };
 use POSIX;
 use strict;
 use Getopt::Long;
```

I tested this by adding `print("$utf8::all::VERSION\n");` to confirm that the module had been imported on systems where the `utf8::all` module is installed.  I couldn't come up with a more thorough way to test the module had been imported and would do what it intended after a quick look at the module's documentation.

**Comment by sawolf** [comment]
Your patch seems correct to me. I verified it against a couple of VMs using `print length 'føø bār';` just after the eval statement (prints 7 if utf-8 is enabled, 10 otherwise).

Thanks for your help with this. I've added your diff to maint and added you to the contributors file.

**Comment by tmzullinger** [comment]
Thank you @sawolf for helping to quickly work this out to allow support for older systems!

**Pull request closed without merging**
