### PR TITLE
Added performance data to the --metric options.

### PR DESCRIPTION
**Pull request by azthec**
This allows for the use in time-series graphing dashboards such as Prometheus and Grafana.

### CODE REVIEW

**Comment by Madlohe** [comment]
Hey, thanks for contributing!

One thing though: would you be able to either omit the changes in line-endings or put them in a separate commit? As it stands, it's difficult to tell what changes you've made here.

**Comment by Madlohe** [comment]
Moving the base to maint, when combined with the whitespace changes, makes this unmergeable. If this is fixed, I'll be happy to merge the PR. In the meantime, I'm going to take it off the 2.3 milestone.

**Comment by azthec** [comment]
Apologies for the mess with closing the pull request and all.

Is [this ](https://github.com/azthec/nagios-plugins/commit/130ed4ca4ff1e5d4aa6787f5e3285ffd67e5801f) the fix you were asking for?

**Comment by Madlohe** [comment]
Yes, this looks good to me. Thanks!

**Pull request merged**
