### PR TITLE
Don’t prematurely report success when checking HTTP TLS cert validity

### PR DESCRIPTION
**Pull request by cpfair**
As it stands, if you specify `-C ...` to check certificate validity with `check_http`, all other conditions are ignored. The server could drop the connection immediately after the TLS handshake, and the "HTTP check" would still succeed. This is different from the standard conjunctive nature of check conditions, and is not documented as such, so it's quite a gotcha: a service could be 100% dead and this check would still be green.

Before (check expects 200, would get 403, still succeeds):
```
check_http 104.20.4.224 --sni --ssl -C 30 --expect 200; echo $?
OK - Certificate 'ssl439398.cloudflaressl.com' will expire on 2017-06-08 19:59 -0400/EDT.
0
```

After (check expects 200, gets 403, fails as expected):
```
check_http 104.20.4.224 --sni --ssl -C 30 --expect 200; echo $?
SSL OK - Certificate 'ssl439398.cloudflaressl.com' will expire on 2017-06-08 19:59 -0400/EDT. HTTP CRITICAL - Invalid HTTP response received from host on port 443: HTTP/1.1 403 Forbidden
2
```

As above, this change also tweaks the output format: The SSL status is prefixed with "SSL" to make it more obvious that the SSL state is separate from the HTTP state. The two status messages also now appear on the same line, so that they're sure to make it into `$SERVICESTATUS$` (rather than just the SSL status, which may not be the cause of the failure). These output changes also apply to check_tcp. If grepping check_http/tcp output with line-start anchors is a common practice, it might be a good idea not to make these changes and to keep the current behaviour. 

This is a breaking change, in that anyone who upgrades will immediately discover which checks have been reporting false positives for the last however-long.

### CODE REVIEW

**Comment by jfrickson** [comment]
There were some conflicts that prevented automatically merging.
See commit https://github.com/nagios-plugins/nagios-plugins/commit/155599c532cc19940b9263bf0b1033ba8d215758

**Comment by chruss2** [comment]
@jfrickson, I suspect you didn't resolve conflicts correctly.  In check_http.c, it now does a close(sd) after np_net_ssl_cleanup(), but it needs to go before to support OpenSSL 1.1 (see commit c6577609).

**Comment by jfrickson** [comment]
Thanks, it will be fixed in a few minutes.

**Comment by bluikko** [comment]
The earlier behavior (check only certificate) was the correct and documented functionality, from check_http manual:
"
 -C, --certificate=INTEGER[,INTEGER]
        Minimum number of days a certificate has to be valid. Port defaults to 443
        (when this option is used the URL is not checked.)
"

It is *not even supposed to* do anything else than check certificate. This pull has broken countless checks...

**Pull request closed without merging**
