### PR TITLE
Update check_file_age.pl

### PR DESCRIPTION
**Pull request by kentgs**
Use the FindBin method to set Nagios plugin directory, to allow the plugin to be executed from arbitrary locations. This removes the requirement for the nagios users home directory to be the plugins directory.

### CODE REVIEW

**Comment by tmcnag** [comment]
Probably should be added to the following as well:

https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-scripts/check_mssql.pl
https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-scripts/check_ntp.pl

**Comment by kentgs** [comment]
Thanks for those suggestions tmcnag.  I've added those to the branch.

**Comment by tmcnag** [comment]
I see no reason why this shouldn't be accepted.  @jfrickson would you care to pull the trigger?

**Comment by waja** [comment]
@jfrickson could you please enlighten us why you closed this PR?

**Comment by glensc** [comment]
#109 was marked duplicate of #106, but in #106 nothing done, #109 explains the problems including actual error that is happening. without the fixes the check_file_age is not usable from nagios (it may work only in git checkout)

**Comment by jfrickson** [comment]
Closed by mistake. Sorry.

**Comment by jfrickson** [comment]
I checked and this was applied to the maint branch. So closing it again.

**Pull request closed without merging**
