### PR TITLE
Add calling-station-id in check_radius

### PR DESCRIPTION
**Pull request by cejkar**
Tested on FreeBSD. It should work on Linux too, but I have no Linux system to really test it.

However, creating portable code for mapping IP address to MAC address is very hard to do, so maybe just explicit -c option would be sufficient. On the other side, it would be a shame not to have it...

### CODE REVIEW

**Comment by hedenface** [comment]
It would be nice to have someone test this before a merge happens. I'll get around to it, it just may take a while :)

@tmcnag @ggonzalez2 @tgriep @douglasawh @ssaxnagios @box293 Any takers?

**Comment by hedenface** [comment]
I merged it - and thank you - but it's only in here tentatively - it *NEEDS* to work on Linux before we can release it.

**Comment by hedenface** [comment]
For commit accountability only, here is the follow up commit for changelog/thanks additions: https://github.com/nagios-plugins/nagios-plugins/commit/3bc54e44481c7b441622cc5b90ed5332a67e751e

**Comment by hedenface** [comment]
@box293 Are you able to test this by chance?

**Comment by box293** [comment]
I did a crash course in getting a freeradius server up and running but I don't know how to get the server to require `calling-station-id`. If I try it just works but I didn't configure anything on the freeradius server:

```
/usr/local/nagios/libexec/check_radius -P 1812 -H 10.25.13.79 -F /etc/radiusclient/test.conf -u testing -p password --calling-station-id=something

Auth OK
```

@cejkar Can you please share the freeradius configuration so I can test.

**Pull request merged**
