### PR TITLE
Add a divisor option to check_snmp

### PR DESCRIPTION
**Pull request by nielsendres**
Give check_snmp the ability to divide the result from an OID or set of OIDs.  Commonly needed when monitoring temperatures (div/10) or converting seconds to minutes (div/60).  Result remains an integer so loss of precision will occur, but existing integer comparisons continue to function.

### CODE REVIEW

**Comment by abrist** [comment]
We could pull in $(MATHLIBS) to do proper division as well.  Thoughts?

**Comment by hedenface** [comment]
Believe it or not, I committed code to do this same thing several years ago - before I worked here! Not sure what happened to it, though. This is cool, I'll take a look and try to get it committed. @nielsendres Is there anyway you'd be able to fix it to merge with the current branch of maint? Sorry about taking so long to get back to you.

**Comment by hedenface** [comment]
Haha! Mine was the next PR in the list as I'm going through them! Check this out: #66 

We'll get it all sorted :)

**Comment by box293** [comment]
As well as dividing, multiplying would also be a good option.

**Comment by k0ste** [comment]
Very useful, I need one divisor /10, and another /1000 for temperature sensors. Works fine.

**Comment by hedenface** [comment]
I just closed #66 for the same reason I'm going to close this: this is going to be done in plugins3, and it'll be included from the getgo in the baseline functionality!

Thank you for the contribution though!

**Pull request closed without merging**
